Vagrant.configure("2") do |config|

  BOX_NAME = "generic/rocky9"

  nodes = {
    "vcs01" => "192.168.56.31",
    "vcs02" => "192.168.56.32"
  }

  nodes.each do |hostname, ip|

    config.vm.define hostname do |node|

      node.vm.box = BOX_NAME
      node.vm.hostname = hostname

      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 6144
        vb.cpus   = 2

        # Shared disks will be attached in the next part.
      end

      node.vm.synced_folder "./software", "/software"
      node.vm.synced_folder "./configs", "/configs"
      node.vm.synced_folder "./scripts", "/scripts"

      node.vm.provision "shell", path: "scripts/01-common.sh"

    end
  end

end
