# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  BOX = "generic/rocky9"

  HOSTS = <<-EOF
192.168.56.10 katello.lab.example.com katello
192.168.56.11 client1.lab.example.com client1
192.168.56.12 client2.lab.example.com client2
EOF

##############################################################
# Katello Server
##############################################################

config.vm.define "katello" do |katello|

  katello.vm.box = BOX

  katello.vm.hostname = "katello.lab.example.com"

  katello.vm.network "private_network",
    ip: "192.168.56.10"

  katello.vm.provider "virtualbox" do |vb|

      vb.name = "Katello-4.16"

      vb.memory = 12288

      vb.cpus = 4

  end

  katello.vm.synced_folder ".", "/vagrant"

  katello.vm.provision "shell", inline: <<-SHELL

echo "#{HOSTS}" >> /etc/hosts

chmod +x /vagrant/scripts/*.sh

/vagrant/scripts/01-update-hosts.sh

/vagrant/scripts/02-common.sh

SHELL

end

##############################################################
# Client1
##############################################################

config.vm.define "client1" do |client|

client.vm.box = BOX

client.vm.hostname = "client1.lab.example.com"

client.vm.network "private_network",
ip: "192.168.56.11"

client.vm.provider "virtualbox" do |vb|

vb.name="Client1"

vb.memory=2048

vb.cpus=2

end

client.vm.synced_folder ".", "/vagrant"

client.vm.provision "shell", inline: <<-SHELL

echo "#{HOSTS}" >> /etc/hosts

chmod +x /vagrant/scripts/*.sh

/vagrant/scripts/01-update-hosts.sh

/vagrant/scripts/02-common.sh

SHELL

end

##############################################################
# Client2
##############################################################

config.vm.define "client2" do |client|

client.vm.box=BOX

client.vm.hostname="client2.lab.example.com"

client.vm.network "private_network",
ip:"192.168.56.12"

client.vm.provider "virtualbox" do |vb|

vb.name="Client2"

vb.memory=2048

vb.cpus=2

end

client.vm.synced_folder ".", "/vagrant"

client.vm.provision "shell", inline: <<-SHELL

echo "#{HOSTS}" >> /etc/hosts

chmod +x /vagrant/scripts/*.sh

/vagrant/scripts/01-update-hosts.sh

/vagrant/scripts/02-common.sh

SHELL

end

end
